name: elan
services:
  db:
    image: postgres:latest
    container_name: elan_db
    restart: unless-stopped
    volumes:
      - elan-postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    logging:
      driver: json-file
      options:
        max-size: 50m
    ports:
      - 5432:5432
  redis:
    image: redis:latest
    restart: unless-stopped
    container_name: elan_redis
    command: /bin/sh -c "redis-server"
    logging:
      driver: json-file
      options:
        max-size: 50m
    volumes:
      - elan-redis-data:/data
    ports:
      - 6379:6379
volumes:
  elan-postgres-data: null
  elan-redis-data: null
